// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celar/epochcommit/v1/archive.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ArchivedSeatCommitment is one committee seat's DKG share commitment for one
// epoch, retained in chain state so that accountability evidence stays
// verifiable after a reshare has replaced every live commitment.
//
// The field numbers are the canonical encoding. An entry is hashed in its
// proto encoding under these numbers and no other canonical form exists, so
// they are fixed: the KMS-side reader declares the same four in the same
// order, and the two sides agree by construction rather than by inspection.
type ArchivedSeatCommitment struct {
	// The seat's share commitment for this epoch.
	CommitmentSha256 string `protobuf:"bytes,1,opt,name=commitment_sha256,json=commitmentSha256,proto3" json:"commitment_sha256,omitempty"`
	// Roster digest for this epoch. Roles are per-committee indices, so across
	// a membership change "role 3" alone names nobody; this binds the role to
	// an identity set.
	RosterSha256 string `protobuf:"bytes,2,opt,name=roster_sha256,json=rosterSha256,proto3" json:"roster_sha256,omitempty"`
	// Height at which this epoch was keyed. Evidence claiming service under
	// this epoch at an earlier header height is malformed — nothing can be
	// served under a key that did not yet exist. The verifier enforces this,
	// so the value is an operand of a check rather than a record.
	KeyedHeight uint64 `protobuf:"varint,3,opt,name=keyed_height,json=keyedHeight,proto3" json:"keyed_height,omitempty"`
	// pk_G digest, invariant across epochs: binds the entry to the key it
	// belongs to, so evidence carries a key-identity anchor.
	PkGSha256 string `protobuf:"bytes,4,opt,name=pk_g_sha256,json=pkGSha256,proto3" json:"pk_g_sha256,omitempty"`
}

func (m *ArchivedSeatCommitment) Reset()         { *m = ArchivedSeatCommitment{} }
func (m *ArchivedSeatCommitment) String() string { return proto.CompactTextString(m) }
func (*ArchivedSeatCommitment) ProtoMessage()    {}
func (*ArchivedSeatCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd85b780fea94f03, []int{0}
}
func (m *ArchivedSeatCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ArchivedSeatCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ArchivedSeatCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ArchivedSeatCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchivedSeatCommitment.Merge(m, src)
}
func (m *ArchivedSeatCommitment) XXX_Size() int {
	return m.Size()
}
func (m *ArchivedSeatCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchivedSeatCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_ArchivedSeatCommitment proto.InternalMessageInfo

func (m *ArchivedSeatCommitment) GetCommitmentSha256() string {
	if m != nil {
		return m.CommitmentSha256
	}
	return ""
}

func (m *ArchivedSeatCommitment) GetRosterSha256() string {
	if m != nil {
		return m.RosterSha256
	}
	return ""
}

func (m *ArchivedSeatCommitment) GetKeyedHeight() uint64 {
	if m != nil {
		return m.KeyedHeight
	}
	return 0
}

func (m *ArchivedSeatCommitment) GetPkGSha256() string {
	if m != nil {
		return m.PkGSha256
	}
	return ""
}

func init() {
	proto.RegisterType((*ArchivedSeatCommitment)(nil), "celar.epochcommit.v1.ArchivedSeatCommitment")
}

func init() {
	proto.RegisterFile("celar/epochcommit/v1/archive.proto", fileDescriptor_cd85b780fea94f03)
}

var fileDescriptor_cd85b780fea94f03 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x4e, 0xcd, 0x49,
	0x2c, 0xd2, 0x4f, 0x2d, 0xc8, 0x4f, 0xce, 0x48, 0xce, 0xcf, 0xcd, 0xcd, 0x2c, 0xd1, 0x2f, 0x33,
	0xd4, 0x4f, 0x2c, 0x4a, 0xce, 0xc8, 0x2c, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12,
	0x01, 0xab, 0xd1, 0x43, 0x52, 0xa3, 0x57, 0x66, 0xa8, 0xb4, 0x96, 0x91, 0x4b, 0xcc, 0x11, 0xa2,
	0x2e, 0x25, 0x38, 0x35, 0xb1, 0xc4, 0x19, 0x2c, 0x93, 0x9b, 0x9a, 0x57, 0x22, 0xa4, 0xcd, 0x25,
	0x98, 0x0c, 0xe7, 0xc5, 0x17, 0x67, 0x24, 0x1a, 0x99, 0x9a, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x09, 0x20, 0x24, 0x82, 0xc1, 0xe2, 0x42, 0xca, 0x5c, 0xbc, 0x45, 0xf9, 0xc5, 0x25, 0xa9,
	0x45, 0x30, 0x85, 0x4c, 0x60, 0x85, 0x3c, 0x10, 0x41, 0xa8, 0x22, 0x45, 0x2e, 0x9e, 0xec, 0xd4,
	0xca, 0xd4, 0x94, 0xf8, 0x8c, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x96,
	0x20, 0x6e, 0xb0, 0x98, 0x07, 0x58, 0x48, 0x48, 0x8e, 0x8b, 0xbb, 0x20, 0x3b, 0x3e, 0x1d, 0x66,
	0x0a, 0x0b, 0xd8, 0x14, 0xce, 0x82, 0x6c, 0x77, 0x88, 0x11, 0x4e, 0x6e, 0x27, 0x1e, 0xc9, 0x31,
	0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb,
	0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x93, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c,
	0x9f, 0xab, 0x9f, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0xac, 0x9f, 0x5a, 0x96, 0x0b, 0xc2, 0x29, 0x28,
	0x01, 0x53, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x0e, 0x14, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdb, 0xf7, 0x84, 0x72, 0x3a, 0x01, 0x00, 0x00,
}

func (m *ArchivedSeatCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ArchivedSeatCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ArchivedSeatCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PkGSha256) > 0 {
		i -= len(m.PkGSha256)
		copy(dAtA[i:], m.PkGSha256)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.PkGSha256)))
		i--
		dAtA[i] = 0x22
	}
	if m.KeyedHeight != 0 {
		i = encodeVarintArchive(dAtA, i, uint64(m.KeyedHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RosterSha256) > 0 {
		i -= len(m.RosterSha256)
		copy(dAtA[i:], m.RosterSha256)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.RosterSha256)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CommitmentSha256) > 0 {
		i -= len(m.CommitmentSha256)
		copy(dAtA[i:], m.CommitmentSha256)
		i = encodeVarintArchive(dAtA, i, uint64(len(m.CommitmentSha256)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintArchive(dAtA []byte, offset int, v uint64) int {
	offset -= sovArchive(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ArchivedSeatCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CommitmentSha256)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	l = len(m.RosterSha256)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	if m.KeyedHeight != 0 {
		n += 1 + sovArchive(uint64(m.KeyedHeight))
	}
	l = len(m.PkGSha256)
	if l > 0 {
		n += 1 + l + sovArchive(uint64(l))
	}
	return n
}

func sovArchive(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozArchive(x uint64) (n int) {
	return sovArchive(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ArchivedSeatCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ArchivedSeatCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ArchivedSeatCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RosterSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RosterSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyedHeight", wireType)
			}
			m.KeyedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PkGSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthArchive
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthArchive
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PkGSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipArchive(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthArchive
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipArchive(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowArchive
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowArchive
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthArchive
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupArchive
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthArchive
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthArchive        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowArchive          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupArchive = fmt.Errorf("proto: unexpected end of group")
)
