// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celar/epochcommit/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ArchiveEntry is one stored commitment together with the key it lives under.
type ArchiveEntry struct {
	Epoch      uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SeatRole   uint32                 `protobuf:"varint,2,opt,name=seat_role,json=seatRole,proto3" json:"seat_role,omitempty"`
	Commitment ArchivedSeatCommitment `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment"`
}

func (m *ArchiveEntry) Reset()         { *m = ArchiveEntry{} }
func (m *ArchiveEntry) String() string { return proto.CompactTextString(m) }
func (*ArchiveEntry) ProtoMessage()    {}
func (*ArchiveEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{0}
}
func (m *ArchiveEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ArchiveEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ArchiveEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ArchiveEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveEntry.Merge(m, src)
}
func (m *ArchiveEntry) XXX_Size() int {
	return m.Size()
}
func (m *ArchiveEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveEntry proto.InternalMessageInfo

func (m *ArchiveEntry) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ArchiveEntry) GetSeatRole() uint32 {
	if m != nil {
		return m.SeatRole
	}
	return 0
}

func (m *ArchiveEntry) GetCommitment() ArchivedSeatCommitment {
	if m != nil {
		return m.Commitment
	}
	return ArchivedSeatCommitment{}
}

// GenesisState is the whole archive plus its retention bounds.
//
// The bounds are carried explicitly rather than derived from the entries.
// Once an epoch has been pruned its entries are gone, but the horizon above
// them is what makes evidence from that epoch read as time-barred rather than
// as naming an epoch that never existed. Deriving bounds from a shortened
// entry list would turn exoneration into a forgery finding.
type GenesisState struct {
	Entries []ArchiveEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
	// Whether the bounds below are meaningful. A chain that has never keyed an
	// epoch has no horizon, and zero is a legitimate epoch number, so absence
	// cannot be encoded as zero.
	BoundsSet           bool   `protobuf:"varint,2,opt,name=bounds_set,json=boundsSet,proto3" json:"bounds_set,omitempty"`
	OldestRetainedEpoch uint64 `protobuf:"varint,3,opt,name=oldest_retained_epoch,json=oldestRetainedEpoch,proto3" json:"oldest_retained_epoch,omitempty"`
	LatestEpoch         uint64 `protobuf:"varint,4,opt,name=latest_epoch,json=latestEpoch,proto3" json:"latest_epoch,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetEntries() []ArchiveEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *GenesisState) GetBoundsSet() bool {
	if m != nil {
		return m.BoundsSet
	}
	return false
}

func (m *GenesisState) GetOldestRetainedEpoch() uint64 {
	if m != nil {
		return m.OldestRetainedEpoch
	}
	return 0
}

func (m *GenesisState) GetLatestEpoch() uint64 {
	if m != nil {
		return m.LatestEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*ArchiveEntry)(nil), "celar.epochcommit.v1.ArchiveEntry")
	proto.RegisterType((*GenesisState)(nil), "celar.epochcommit.v1.GenesisState")
}

func init() {
	proto.RegisterFile("celar/epochcommit/v1/genesis.proto", fileDescriptor_740d85f23b645741)
}

var fileDescriptor_740d85f23b645741 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xb1, 0x6e, 0xe2, 0x40,
	0x10, 0x86, 0xbd, 0x07, 0x77, 0x07, 0x0b, 0xd7, 0xf8, 0x88, 0x64, 0x11, 0xc5, 0x71, 0x5c, 0xb9,
	0x40, 0xb6, 0x20, 0x4f, 0x10, 0x22, 0x92, 0x7e, 0xe9, 0xd2, 0x58, 0x8b, 0x3d, 0x32, 0x96, 0x6c,
	0x2f, 0xda, 0x1d, 0x2c, 0xf1, 0x16, 0x69, 0xf2, 0x4e, 0x94, 0x94, 0xa9, 0xa2, 0x08, 0x5e, 0x24,
	0xf2, 0x2e, 0x89, 0x88, 0x84, 0x52, 0x58, 0x1a, 0xff, 0xf3, 0xfd, 0x33, 0x3b, 0x33, 0xd4, 0x4f,
	0xa0, 0xe0, 0x32, 0x82, 0x95, 0x48, 0x96, 0x89, 0x28, 0xcb, 0x1c, 0xa3, 0x7a, 0x1c, 0x65, 0x50,
	0x81, 0xca, 0x55, 0xb8, 0x92, 0x02, 0x85, 0x3d, 0xd0, 0x4c, 0x78, 0xc2, 0x84, 0xf5, 0x78, 0x78,
	0xde, 0xc9, 0x65, 0xb2, 0xcc, 0x6b, 0x30, 0xce, 0xe1, 0x20, 0x13, 0x99, 0xd0, 0x61, 0xd4, 0x44,
	0x46, 0xf5, 0x5f, 0x08, 0xed, 0xdf, 0x19, 0x6e, 0x56, 0xa1, 0xdc, 0xd8, 0x03, 0xfa, 0x5b, 0x97,
	0x71, 0x88, 0x47, 0x82, 0x36, 0x33, 0x3f, 0xf6, 0x25, 0xed, 0x2a, 0xe0, 0x18, 0x4b, 0x51, 0x80,
	0xf3, 0xcb, 0x23, 0xc1, 0x3f, 0xd6, 0x69, 0x04, 0x26, 0x0a, 0xb0, 0x19, 0xa5, 0xa6, 0x69, 0x09,
	0x15, 0x3a, 0x2d, 0x8f, 0x04, 0xbd, 0xc9, 0x28, 0x3c, 0xf7, 0xd0, 0xf0, 0xd8, 0x2a, 0x9d, 0x03,
	0xc7, 0xfb, 0x2f, 0xcf, 0xb4, 0xbd, 0x7d, 0xbb, 0xb6, 0xd8, 0x49, 0x15, 0x7f, 0x4b, 0x68, 0xff,
	0xd1, 0x4c, 0x3e, 0x47, 0x8e, 0x60, 0x4f, 0xe9, 0x5f, 0xa8, 0x50, 0xe6, 0xa0, 0x1c, 0xe2, 0xb5,
	0x82, 0xde, 0xc4, 0xff, 0xb1, 0x83, 0x1e, 0xe6, 0x58, 0xf7, 0xd3, 0x68, 0x5f, 0x51, 0xba, 0x10,
	0xeb, 0x2a, 0x55, 0xb1, 0x02, 0xd4, 0x63, 0x74, 0x58, 0xd7, 0x28, 0x73, 0x40, 0x7b, 0x42, 0x2f,
	0x44, 0x91, 0x82, 0xc2, 0x58, 0x02, 0xf2, 0xbc, 0x82, 0x34, 0x36, 0xab, 0x68, 0xe9, 0x55, 0xfc,
	0x37, 0x49, 0x76, 0xcc, 0xcd, 0xf4, 0x62, 0x6e, 0x68, 0xbf, 0xe0, 0xd8, 0x78, 0x0c, 0xda, 0xd6,
	0x68, 0xcf, 0x68, 0x1a, 0x99, 0x3e, 0x6c, 0xf7, 0x2e, 0xd9, 0xed, 0x5d, 0xf2, 0xbe, 0x77, 0xc9,
	0xf3, 0xc1, 0xb5, 0x76, 0x07, 0xd7, 0x7a, 0x3d, 0xb8, 0xd6, 0xd3, 0x28, 0xcb, 0x71, 0xb9, 0x5e,
	0x84, 0x89, 0x28, 0xa3, 0x44, 0xa8, 0x52, 0xa8, 0x08, 0xea, 0xb2, 0xf9, 0xd2, 0x6f, 0xb7, 0xc4,
	0xcd, 0x0a, 0xd4, 0xe2, 0x8f, 0xbe, 0xd8, 0xed, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x4d,
	0x14, 0x10, 0x27, 0x02, 0x00, 0x00,
}

func (m *ArchiveEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ArchiveEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ArchiveEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Commitment.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.SeatRole != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SeatRole))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LatestEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.OldestRetainedEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.OldestRetainedEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.BoundsSet {
		i--
		if m.BoundsSet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ArchiveEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	if m.SeatRole != 0 {
		n += 1 + sovGenesis(uint64(m.SeatRole))
	}
	l = m.Commitment.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BoundsSet {
		n += 2
	}
	if m.OldestRetainedEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.OldestRetainedEpoch))
	}
	if m.LatestEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.LatestEpoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ArchiveEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ArchiveEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ArchiveEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeatRole", wireType)
			}
			m.SeatRole = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeatRole |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commitment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, ArchiveEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoundsSet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BoundsSet = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldestRetainedEpoch", wireType)
			}
			m.OldestRetainedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldestRetainedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestEpoch", wireType)
			}
			m.LatestEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
