// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celar/epochcommit/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ArchiveEntry is one stored commitment together with the key it lives under.
type ArchiveEntry struct {
	Epoch      uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SeatRole   uint32                 `protobuf:"varint,2,opt,name=seat_role,json=seatRole,proto3" json:"seat_role,omitempty"`
	Commitment ArchivedSeatCommitment `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment"`
}

func (m *ArchiveEntry) Reset()         { *m = ArchiveEntry{} }
func (m *ArchiveEntry) String() string { return proto.CompactTextString(m) }
func (*ArchiveEntry) ProtoMessage()    {}
func (*ArchiveEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{0}
}
func (m *ArchiveEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ArchiveEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ArchiveEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ArchiveEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveEntry.Merge(m, src)
}
func (m *ArchiveEntry) XXX_Size() int {
	return m.Size()
}
func (m *ArchiveEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveEntry proto.InternalMessageInfo

func (m *ArchiveEntry) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *ArchiveEntry) GetSeatRole() uint32 {
	if m != nil {
		return m.SeatRole
	}
	return 0
}

func (m *ArchiveEntry) GetCommitment() ArchivedSeatCommitment {
	if m != nil {
		return m.Commitment
	}
	return ArchivedSeatCommitment{}
}

// GenesisState is the whole archive plus its retention bounds.
//
// The bounds are carried explicitly rather than derived from the entries.
// Once an epoch has been pruned its entries are gone, but the horizon above
// them is what makes evidence from that epoch read as time-barred rather than
// as naming an epoch that never existed. Deriving bounds from a shortened
// entry list would turn exoneration into a forgery finding.
// EpochHorizon is the height past which an epoch's evidence is no longer
// punishable. Chain-local bookkeeping: it is deliberately NOT part of
// ArchivedSeatCommitment, whose four fields are the canonical encoding agreed
// with the reader, and it is not on the proof path.
type EpochHorizon struct {
	Epoch        uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ExpiryHeight uint64 `protobuf:"varint,2,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
}

func (m *EpochHorizon) Reset()         { *m = EpochHorizon{} }
func (m *EpochHorizon) String() string { return proto.CompactTextString(m) }
func (*EpochHorizon) ProtoMessage()    {}
func (*EpochHorizon) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{1}
}
func (m *EpochHorizon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochHorizon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochHorizon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochHorizon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochHorizon.Merge(m, src)
}
func (m *EpochHorizon) XXX_Size() int {
	return m.Size()
}
func (m *EpochHorizon) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochHorizon.DiscardUnknown(m)
}

var xxx_messageInfo_EpochHorizon proto.InternalMessageInfo

func (m *EpochHorizon) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochHorizon) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

// TranscriptDigest is the digest of the ceremony transcript that established
// an epoch. A submission names the digest it chains from; that claim is
// checked against the stored value for the preceding epoch.
type TranscriptDigest struct {
	Epoch  uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (m *TranscriptDigest) Reset()         { *m = TranscriptDigest{} }
func (m *TranscriptDigest) String() string { return proto.CompactTextString(m) }
func (*TranscriptDigest) ProtoMessage()    {}
func (*TranscriptDigest) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{2}
}
func (m *TranscriptDigest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TranscriptDigest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TranscriptDigest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TranscriptDigest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranscriptDigest.Merge(m, src)
}
func (m *TranscriptDigest) XXX_Size() int {
	return m.Size()
}
func (m *TranscriptDigest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranscriptDigest.DiscardUnknown(m)
}

var xxx_messageInfo_TranscriptDigest proto.InternalMessageInfo

func (m *TranscriptDigest) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *TranscriptDigest) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

type GenesisState struct {
	Entries []ArchiveEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
	// Whether the bounds below are meaningful. A chain that has never keyed an
	// epoch has no horizon, and zero is a legitimate epoch number, so absence
	// cannot be encoded as zero.
	BoundsSet           bool   `protobuf:"varint,2,opt,name=bounds_set,json=boundsSet,proto3" json:"bounds_set,omitempty"`
	OldestRetainedEpoch uint64 `protobuf:"varint,3,opt,name=oldest_retained_epoch,json=oldestRetainedEpoch,proto3" json:"oldest_retained_epoch,omitempty"`
	LatestEpoch         uint64 `protobuf:"varint,4,opt,name=latest_epoch,json=latestEpoch,proto3" json:"latest_epoch,omitempty"`
	// Carried explicitly: without them a restored chain cannot prune, and
	// cannot show why it is not pruning.
	Horizons []EpochHorizon `protobuf:"bytes,5,rep,name=horizons,proto3" json:"horizons"`
	// Carried so a restored chain can still check the chain linkage of a
	// submission against the epoch before it.
	Transcripts []TranscriptDigest `protobuf:"bytes,6,rep,name=transcripts,proto3" json:"transcripts"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_740d85f23b645741, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetEntries() []ArchiveEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *GenesisState) GetBoundsSet() bool {
	if m != nil {
		return m.BoundsSet
	}
	return false
}

func (m *GenesisState) GetOldestRetainedEpoch() uint64 {
	if m != nil {
		return m.OldestRetainedEpoch
	}
	return 0
}

func (m *GenesisState) GetLatestEpoch() uint64 {
	if m != nil {
		return m.LatestEpoch
	}
	return 0
}

func (m *GenesisState) GetHorizons() []EpochHorizon {
	if m != nil {
		return m.Horizons
	}
	return nil
}

func (m *GenesisState) GetTranscripts() []TranscriptDigest {
	if m != nil {
		return m.Transcripts
	}
	return nil
}

func init() {
	proto.RegisterType((*ArchiveEntry)(nil), "celar.epochcommit.v1.ArchiveEntry")
	proto.RegisterType((*EpochHorizon)(nil), "celar.epochcommit.v1.EpochHorizon")
	proto.RegisterType((*TranscriptDigest)(nil), "celar.epochcommit.v1.TranscriptDigest")
	proto.RegisterType((*GenesisState)(nil), "celar.epochcommit.v1.GenesisState")
}

func init() {
	proto.RegisterFile("celar/epochcommit/v1/genesis.proto", fileDescriptor_740d85f23b645741)
}

var fileDescriptor_740d85f23b645741 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0x8c, 0x9b, 0x34, 0x24, 0x2f, 0xa9, 0x84, 0x4c, 0x40, 0x56, 0x11, 0x26, 0x18, 0x09, 0xe5,
	0x50, 0xd9, 0x6a, 0x10, 0x9c, 0x21, 0xb4, 0x50, 0x2e, 0x1c, 0x1c, 0x4e, 0x5c, 0xac, 0x8d, 0xfd,
	0x64, 0xaf, 0x64, 0x7b, 0xad, 0xdd, 0xd7, 0x88, 0xf0, 0x15, 0x5c, 0xf8, 0xa7, 0x1e, 0x7b, 0xe4,
	0x54, 0xa1, 0xe4, 0x47, 0x90, 0x77, 0x4d, 0x14, 0xaa, 0xb4, 0x07, 0x4b, 0xbb, 0xb3, 0x33, 0xb3,
	0xb3, 0xe3, 0x07, 0x5e, 0x8c, 0x39, 0x93, 0x01, 0x56, 0x22, 0xce, 0x62, 0x51, 0x14, 0x9c, 0x82,
	0xe5, 0x69, 0x90, 0x62, 0x89, 0x8a, 0x2b, 0xbf, 0x92, 0x82, 0x84, 0x3d, 0xd2, 0x1c, 0x7f, 0x87,
	0xe3, 0x2f, 0x4f, 0x8f, 0xf7, 0x2b, 0x99, 0x8c, 0x33, 0xbe, 0x44, 0xa3, 0x3c, 0x1e, 0xa5, 0x22,
	0x15, 0x7a, 0x19, 0xd4, 0x2b, 0x83, 0x7a, 0xbf, 0x2c, 0x18, 0xbe, 0x37, 0xbc, 0xf3, 0x92, 0xe4,
	0xca, 0x1e, 0xc1, 0xa1, 0xb6, 0x71, 0xac, 0xb1, 0x35, 0xe9, 0x84, 0x66, 0x63, 0x3f, 0x85, 0xbe,
	0x42, 0x46, 0x91, 0x14, 0x39, 0x3a, 0x07, 0x63, 0x6b, 0x72, 0x14, 0xf6, 0x6a, 0x20, 0x14, 0x39,
	0xda, 0x21, 0x80, 0xb9, 0xb4, 0xc0, 0x92, 0x9c, 0xf6, 0xd8, 0x9a, 0x0c, 0xa6, 0x27, 0xfe, 0xbe,
	0xa0, 0x7e, 0x73, 0x55, 0x32, 0x47, 0x46, 0x1f, 0xb6, 0x9a, 0x59, 0xe7, 0xea, 0xe6, 0x79, 0x2b,
	0xdc, 0x71, 0xf1, 0x3e, 0xc3, 0xf0, 0xbc, 0x96, 0x5e, 0x08, 0xc9, 0x7f, 0x88, 0xf2, 0x8e, 0x58,
	0x2f, 0xe1, 0x08, 0xbf, 0x57, 0x5c, 0xae, 0xa2, 0x0c, 0x79, 0x9a, 0x91, 0x8e, 0xd6, 0x09, 0x87,
	0x06, 0xbc, 0xd0, 0x98, 0xf7, 0x0e, 0x1e, 0x7e, 0x95, 0xac, 0x54, 0xb1, 0xe4, 0x15, 0x9d, 0xf1,
	0x14, 0x15, 0xdd, 0x61, 0xf7, 0x04, 0xba, 0x2a, 0x63, 0xd3, 0x37, 0x6f, 0xb5, 0x4f, 0x3f, 0x6c,
	0x76, 0xde, 0xcd, 0x01, 0x0c, 0x3f, 0x99, 0xdf, 0x30, 0x27, 0x46, 0x68, 0xcf, 0xe0, 0x01, 0x96,
	0x24, 0x39, 0x2a, 0xc7, 0x1a, 0xb7, 0x27, 0x83, 0xa9, 0x77, 0xef, 0x73, 0x75, 0xb3, 0xcd, 0x23,
	0xff, 0x09, 0xed, 0x67, 0x00, 0x0b, 0x71, 0x59, 0x26, 0x2a, 0x52, 0x68, 0x82, 0xf7, 0xc2, 0xbe,
	0x41, 0xe6, 0x48, 0xf6, 0x14, 0x1e, 0x8b, 0x3c, 0x41, 0x45, 0x91, 0x44, 0x62, 0xbc, 0xc4, 0x24,
	0x32, 0x89, 0xdb, 0x3a, 0xf1, 0x23, 0x73, 0x18, 0x36, 0x67, 0xba, 0x2b, 0xfb, 0x05, 0x0c, 0x73,
	0x46, 0xb5, 0xc6, 0x50, 0x3b, 0x9a, 0x3a, 0x30, 0x98, 0xa1, 0x9c, 0x41, 0x2f, 0x33, 0x95, 0x2a,
	0xe7, 0xf0, 0xbe, 0xe8, 0xbb, 0xed, 0x37, 0xd1, 0xb7, 0x4a, 0xfb, 0x0b, 0x0c, 0x68, 0x5b, 0xa9,
	0x72, 0xba, 0xda, 0xe8, 0xd5, 0x7e, 0xa3, 0xdb, 0xdd, 0x37, 0x66, 0xbb, 0x06, 0xb3, 0x8f, 0x57,
	0x6b, 0xd7, 0xba, 0x5e, 0xbb, 0xd6, 0x9f, 0xb5, 0x6b, 0xfd, 0xdc, 0xb8, 0xad, 0xeb, 0x8d, 0xdb,
	0xfa, 0xbd, 0x71, 0x5b, 0xdf, 0x4e, 0x52, 0x4e, 0xd9, 0xe5, 0xc2, 0x8f, 0x45, 0x11, 0xc4, 0x42,
	0x15, 0x42, 0x05, 0xb8, 0x2c, 0xea, 0x2f, 0xf9, 0x6f, 0xdc, 0x69, 0x55, 0xa1, 0x5a, 0x74, 0xf5,
	0x50, 0xbf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x5b, 0x53, 0x73, 0x4a, 0x03, 0x00, 0x00,
}

func (m *ArchiveEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ArchiveEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ArchiveEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Commitment.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.SeatRole != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SeatRole))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EpochHorizon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochHorizon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochHorizon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiryHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TranscriptDigest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TranscriptDigest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TranscriptDigest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sha256) > 0 {
		i -= len(m.Sha256)
		copy(dAtA[i:], m.Sha256)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Sha256)))
		i--
		dAtA[i] = 0x12
	}
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Transcripts) > 0 {
		for iNdEx := len(m.Transcripts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Transcripts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Horizons) > 0 {
		for iNdEx := len(m.Horizons) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Horizons[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.LatestEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LatestEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.OldestRetainedEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.OldestRetainedEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.BoundsSet {
		i--
		if m.BoundsSet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ArchiveEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	if m.SeatRole != 0 {
		n += 1 + sovGenesis(uint64(m.SeatRole))
	}
	l = m.Commitment.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *EpochHorizon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovGenesis(uint64(m.ExpiryHeight))
	}
	return n
}

func (m *TranscriptDigest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	l = len(m.Sha256)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BoundsSet {
		n += 2
	}
	if m.OldestRetainedEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.OldestRetainedEpoch))
	}
	if m.LatestEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.LatestEpoch))
	}
	if len(m.Horizons) > 0 {
		for _, e := range m.Horizons {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Transcripts) > 0 {
		for _, e := range m.Transcripts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ArchiveEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ArchiveEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ArchiveEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeatRole", wireType)
			}
			m.SeatRole = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeatRole |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Commitment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochHorizon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochHorizon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochHorizon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TranscriptDigest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TranscriptDigest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TranscriptDigest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, ArchiveEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoundsSet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BoundsSet = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldestRetainedEpoch", wireType)
			}
			m.OldestRetainedEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldestRetainedEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestEpoch", wireType)
			}
			m.LatestEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Horizons", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Horizons = append(m.Horizons, EpochHorizon{})
			if err := m.Horizons[len(m.Horizons)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transcripts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transcripts = append(m.Transcripts, TranscriptDigest{})
			if err := m.Transcripts[len(m.Transcripts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
