// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celar/fraudevidence/v1/attestation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Attestation is a coprocessor's signed claim about one executed operation:
// where it executed from, the handle the chain assigned, and a digest of the
// ciphertext it produced.
//
// Kept in chain state because the result body goes to the availability layer
// and the attestation is what the chain keeps. A sampled re-execution is
// compared against this record, so it has to outlive the block that carried
// it.
//
// Field numbers are canonical from the first byte written, for the reason the
// commitment archive fixed its own.
type Attestation struct {
	// Stream position: height, transaction index, log index.
	//
	// Stored as three fields rather than as the packed key. The packing belongs
	// to key derivation; duplicating it inside the record would give one triple
	// two representations in a single module, which is the drift that pinning
	// the encoding exists to prevent.
	Height   uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	TxIndex  uint32 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	LogIndex uint32 `protobuf:"varint,3,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	// The chain-assigned result handle the operation produced.
	ResultHandle []byte `protobuf:"bytes,4,opt,name=result_handle,json=resultHandle,proto3" json:"result_handle,omitempty"`
	// Digest of the produced ciphertext, over the narrowed basis.
	//
	// Not the admitted-ciphertext commitment: that is a different digest over a
	// different representation, and confusing the two yields 32 plausible bytes
	// that never match.
	CtDigest []byte `protobuf:"bytes,5,opt,name=ct_digest,json=ctDigest,proto3" json:"ct_digest,omitempty"`
	// Commitment-scheme version.
	//
	// Carried although only one scheme exists, because it is what lets a future
	// validity proof arrive as a later version with the handle-to-digest
	// binding unchanged. Adding it after attestations exist would be exactly
	// the state migration it avoids.
	EnvVersion uint32 `protobuf:"varint,6,opt,name=env_version,json=envVersion,proto3" json:"env_version,omitempty"`
	// Who attested, and their signature over the pinned preimage.
	CoprocessorId []byte `protobuf:"bytes,7,opt,name=coprocessor_id,json=coprocessorId,proto3" json:"coprocessor_id,omitempty"`
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8227dba7f60c275, []int{0}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return m.Size()
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Attestation) GetTxIndex() uint32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *Attestation) GetLogIndex() uint32 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

func (m *Attestation) GetResultHandle() []byte {
	if m != nil {
		return m.ResultHandle
	}
	return nil
}

func (m *Attestation) GetCtDigest() []byte {
	if m != nil {
		return m.CtDigest
	}
	return nil
}

func (m *Attestation) GetEnvVersion() uint32 {
	if m != nil {
		return m.EnvVersion
	}
	return 0
}

func (m *Attestation) GetCoprocessorId() []byte {
	if m != nil {
		return m.CoprocessorId
	}
	return nil
}

func (m *Attestation) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Attestation)(nil), "celar.fraudevidence.v1.Attestation")
}

func init() {
	proto.RegisterFile("celar/fraudevidence/v1/attestation.proto", fileDescriptor_a8227dba7f60c275)
}

var fileDescriptor_a8227dba7f60c275 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x6e, 0xea, 0x30,
	0x14, 0x86, 0x31, 0x97, 0x0b, 0xc1, 0xc0, 0x1d, 0x3c, 0x20, 0x5f, 0xdd, 0xab, 0x14, 0xb5, 0xaa,
	0x94, 0x29, 0x11, 0xea, 0x13, 0xb4, 0xea, 0x00, 0x2b, 0x43, 0x87, 0x2e, 0x51, 0xb0, 0x4f, 0x13,
	0x4b, 0xc1, 0x46, 0xf6, 0x89, 0x45, 0x1f, 0xa0, 0x7b, 0x1f, 0xab, 0x23, 0x63, 0xc7, 0x0a, 0x5e,
	0xa4, 0xc2, 0x20, 0xd1, 0x76, 0xf0, 0xf0, 0x7f, 0xff, 0xa7, 0x63, 0xe9, 0xa7, 0x89, 0x80, 0xba,
	0xb0, 0xd9, 0x93, 0x2d, 0x1a, 0x09, 0x5e, 0x49, 0xd0, 0x02, 0x32, 0x3f, 0xcd, 0x0a, 0x44, 0x70,
	0x58, 0xa0, 0x32, 0x3a, 0x5d, 0x5b, 0x83, 0x86, 0x8d, 0x83, 0x99, 0x7e, 0x33, 0x53, 0x3f, 0xbd,
	0x7c, 0x69, 0xd3, 0xc1, 0xed, 0xd9, 0x66, 0x63, 0xda, 0xad, 0x40, 0x95, 0x15, 0x72, 0x32, 0x21,
	0x49, 0x67, 0x71, 0x4a, 0xec, 0x2f, 0x8d, 0x70, 0x93, 0x2b, 0x2d, 0x61, 0xc3, 0xdb, 0x13, 0x92,
	0x8c, 0x16, 0x3d, 0xdc, 0xcc, 0x0f, 0x91, 0xfd, 0xa3, 0xfd, 0xda, 0x94, 0xa7, 0xee, 0x57, 0xe8,
	0xa2, 0xda, 0x94, 0xc7, 0xf2, 0x8a, 0x8e, 0x2c, 0xb8, 0xa6, 0xc6, 0xbc, 0x2a, 0xb4, 0xac, 0x81,
	0x77, 0x26, 0x24, 0x19, 0x2e, 0x86, 0x47, 0x38, 0x0b, 0xec, 0x70, 0x41, 0x60, 0x2e, 0x55, 0x09,
	0x0e, 0xf9, 0xef, 0x20, 0x44, 0x02, 0xef, 0x43, 0x66, 0x17, 0x74, 0x00, 0xda, 0xe7, 0x1e, 0xac,
	0x53, 0x46, 0xf3, 0x6e, 0xf8, 0x80, 0x82, 0xf6, 0x0f, 0x47, 0xc2, 0xae, 0xe9, 0x1f, 0x61, 0xd6,
	0xd6, 0x08, 0x70, 0xce, 0xd8, 0x5c, 0x49, 0xde, 0x0b, 0x27, 0x46, 0x5f, 0xe8, 0x5c, 0xb2, 0xff,
	0xb4, 0xef, 0x54, 0xa9, 0x0b, 0x6c, 0x2c, 0xf0, 0x28, 0x18, 0x67, 0x70, 0x37, 0x7b, 0xdb, 0xc5,
	0x64, 0xbb, 0x8b, 0xc9, 0xc7, 0x2e, 0x26, 0xaf, 0xfb, 0xb8, 0xb5, 0xdd, 0xc7, 0xad, 0xf7, 0x7d,
	0xdc, 0x7a, 0x4c, 0x4b, 0x85, 0x55, 0xb3, 0x4c, 0x85, 0x59, 0x65, 0xc2, 0xb8, 0x95, 0x71, 0x19,
	0xf8, 0xd5, 0xe1, 0xc9, 0x1f, 0xc3, 0xe3, 0xf3, 0x1a, 0xdc, 0xb2, 0x1b, 0x06, 0xbf, 0xf9, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x76, 0x4f, 0x0f, 0x83, 0x9c, 0x01, 0x00, 0x00,
}

func (m *Attestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintAttestation(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CoprocessorId) > 0 {
		i -= len(m.CoprocessorId)
		copy(dAtA[i:], m.CoprocessorId)
		i = encodeVarintAttestation(dAtA, i, uint64(len(m.CoprocessorId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.EnvVersion != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.EnvVersion))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CtDigest) > 0 {
		i -= len(m.CtDigest)
		copy(dAtA[i:], m.CtDigest)
		i = encodeVarintAttestation(dAtA, i, uint64(len(m.CtDigest)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ResultHandle) > 0 {
		i -= len(m.ResultHandle)
		copy(dAtA[i:], m.ResultHandle)
		i = encodeVarintAttestation(dAtA, i, uint64(len(m.ResultHandle)))
		i--
		dAtA[i] = 0x22
	}
	if m.LogIndex != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.LogIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.TxIndex != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.TxIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAttestation(dAtA []byte, offset int, v uint64) int {
	offset -= sovAttestation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Attestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovAttestation(uint64(m.Height))
	}
	if m.TxIndex != 0 {
		n += 1 + sovAttestation(uint64(m.TxIndex))
	}
	if m.LogIndex != 0 {
		n += 1 + sovAttestation(uint64(m.LogIndex))
	}
	l = len(m.ResultHandle)
	if l > 0 {
		n += 1 + l + sovAttestation(uint64(l))
	}
	l = len(m.CtDigest)
	if l > 0 {
		n += 1 + l + sovAttestation(uint64(l))
	}
	if m.EnvVersion != 0 {
		n += 1 + sovAttestation(uint64(m.EnvVersion))
	}
	l = len(m.CoprocessorId)
	if l > 0 {
		n += 1 + l + sovAttestation(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovAttestation(uint64(l))
	}
	return n
}

func sovAttestation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAttestation(x uint64) (n int) {
	return sovAttestation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Attestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxIndex", wireType)
			}
			m.TxIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultHandle", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultHandle = append(m.ResultHandle[:0], dAtA[iNdEx:postIndex]...)
			if m.ResultHandle == nil {
				m.ResultHandle = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CtDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CtDigest = append(m.CtDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.CtDigest == nil {
				m.CtDigest = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnvVersion", wireType)
			}
			m.EnvVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnvVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoprocessorId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoprocessorId = append(m.CoprocessorId[:0], dAtA[iNdEx:postIndex]...)
			if m.CoprocessorId == nil {
				m.CoprocessorId = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAttestation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAttestation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAttestation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAttestation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAttestation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttestation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttestation = fmt.Errorf("proto: unexpected end of group")
)
