// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celar/fraudevidence/v1/verdict.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Verdict is a recorded conviction: one seat, one epoch, and the evidence it
// was convicted on.
//
// It exists as chain state rather than as an event because a conviction has to
// be readable after the block that produced it. A slashing hook consumes it, a
// later submission must not convict the same seat twice for the same evidence,
// and anyone auditing the accountability path needs to see what was decided
// rather than reconstruct it from logs.
//
// Field numbers are the canonical encoding, fixed from the first byte written,
// for the same reason the commitment archive fixed its own: if either side
// ever hashes one of these, it hashes the proto form under these numbers and
// no other canonical form exists.
type Verdict struct {
	// One-based committee role of the convicted seat. Zero is malformed
	// evidence, never a seat.
	SeatRole uint32 `protobuf:"varint,1,opt,name=seat_role,json=seatRole,proto3" json:"seat_role,omitempty"`
	// Key epoch the misconduct occurred under. Pairs with seat_role as the key,
	// matching how the commitment archive names the same thing.
	Epoch uint64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Digest of the evidence that convicted. Recorded so a second submission of
	// the SAME evidence is idempotent rather than a second conviction, and so an
	// auditor can tie a verdict to the material that produced it.
	EvidenceSha256 string `protobuf:"bytes,3,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	// Height at which the conviction was recorded. Distinct from the height the
	// evidence proves against: one is when the misconduct was provable, the
	// other is when the chain acted. Conflating them would make the punishment
	// window unauditable.
	RecordedHeight uint64 `protobuf:"varint,4,opt,name=recorded_height,json=recordedHeight,proto3" json:"recorded_height,omitempty"`
	// Whether punishment has been applied.
	//
	// Deliberately a field rather than an inference from the verdict existing.
	// The punishment hook waits on a decision this module does not own, so for
	// now every verdict is recorded with this false, and a verdict that convicts
	// without punishing is visibly incomplete rather than silently equivalent to
	// one that did. When the hook lands, this is what stops it running twice.
	Punished bool `protobuf:"varint,5,opt,name=punished,proto3" json:"punished,omitempty"`
}

func (m *Verdict) Reset()         { *m = Verdict{} }
func (m *Verdict) String() string { return proto.CompactTextString(m) }
func (*Verdict) ProtoMessage()    {}
func (*Verdict) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2cae61204d78e1, []int{0}
}
func (m *Verdict) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Verdict) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Verdict.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Verdict) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verdict.Merge(m, src)
}
func (m *Verdict) XXX_Size() int {
	return m.Size()
}
func (m *Verdict) XXX_DiscardUnknown() {
	xxx_messageInfo_Verdict.DiscardUnknown(m)
}

var xxx_messageInfo_Verdict proto.InternalMessageInfo

func (m *Verdict) GetSeatRole() uint32 {
	if m != nil {
		return m.SeatRole
	}
	return 0
}

func (m *Verdict) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Verdict) GetEvidenceSha256() string {
	if m != nil {
		return m.EvidenceSha256
	}
	return ""
}

func (m *Verdict) GetRecordedHeight() uint64 {
	if m != nil {
		return m.RecordedHeight
	}
	return 0
}

func (m *Verdict) GetPunished() bool {
	if m != nil {
		return m.Punished
	}
	return false
}

func init() {
	proto.RegisterType((*Verdict)(nil), "celar.fraudevidence.v1.Verdict")
}

func init() {
	proto.RegisterFile("celar/fraudevidence/v1/verdict.proto", fileDescriptor_8d2cae61204d78e1)
}

var fileDescriptor_8d2cae61204d78e1 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0x17, 0xdd, 0xb4, 0x0b, 0x38, 0xa1, 0x88, 0x14, 0x85, 0x50, 0x44, 0xb0, 0xa7, 0x86,
	0x29, 0xfa, 0x00, 0x9e, 0x76, 0x8e, 0xe0, 0xc1, 0x4b, 0xe9, 0x92, 0xbf, 0x4b, 0xa0, 0x5d, 0x4a,
	0x92, 0x06, 0x7c, 0x0b, 0x9f, 0xc3, 0x27, 0xf1, 0xb8, 0xa3, 0x47, 0x69, 0x5f, 0x44, 0x9a, 0x51,
	0x41, 0x0f, 0xdf, 0xe1, 0xfb, 0xf1, 0xe3, 0x3b, 0x7c, 0xf8, 0x9a, 0x43, 0x55, 0x1a, 0xfa, 0x6a,
	0xca, 0x56, 0x80, 0x57, 0x02, 0xb6, 0x1c, 0xa8, 0x5f, 0x52, 0x0f, 0x46, 0x28, 0xee, 0xf2, 0xc6,
	0x68, 0xa7, 0xe3, 0xf3, 0x60, 0xe5, 0x7f, 0xac, 0xdc, 0x2f, 0xaf, 0x3e, 0x10, 0x3e, 0x7e, 0xde,
	0x9b, 0xf1, 0x25, 0x9e, 0x5b, 0x28, 0x5d, 0x61, 0x74, 0x05, 0x09, 0x4a, 0x51, 0x76, 0xc2, 0xa2,
	0x01, 0x30, 0x5d, 0x41, 0x7c, 0x86, 0x67, 0xd0, 0x68, 0x2e, 0x93, 0x83, 0x14, 0x65, 0x53, 0xb6,
	0x2f, 0xf1, 0x0d, 0x3e, 0x1d, 0xd7, 0x0a, 0x2b, 0xcb, 0xdb, 0xfb, 0x87, 0xe4, 0x30, 0x45, 0xd9,
	0x9c, 0x2d, 0x46, 0xfc, 0x14, 0xe8, 0x20, 0x1a, 0xe0, 0xda, 0x08, 0x10, 0x85, 0x04, 0xb5, 0x91,
	0x2e, 0x99, 0x86, 0xa1, 0xc5, 0x88, 0x57, 0x81, 0xc6, 0x17, 0x38, 0x6a, 0xda, 0xad, 0xb2, 0x12,
	0x44, 0x32, 0x4b, 0x51, 0x16, 0xb1, 0xdf, 0xfe, 0xb8, 0xfa, 0xec, 0x08, 0xda, 0x75, 0x04, 0x7d,
	0x77, 0x04, 0xbd, 0xf7, 0x64, 0xb2, 0xeb, 0xc9, 0xe4, 0xab, 0x27, 0x93, 0x97, 0x7c, 0xa3, 0x9c,
	0x6c, 0xd7, 0x39, 0xd7, 0x35, 0xe5, 0xda, 0xd6, 0xda, 0x52, 0xf0, 0xf5, 0x10, 0xf1, 0xef, 0x19,
	0xf7, 0xd6, 0x80, 0x5d, 0x1f, 0x85, 0x57, 0xee, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41, 0x13,
	0x23, 0x44, 0x3d, 0x01, 0x00, 0x00,
}

func (m *Verdict) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Verdict) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Verdict) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Punished {
		i--
		if m.Punished {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.RecordedHeight != 0 {
		i = encodeVarintVerdict(dAtA, i, uint64(m.RecordedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.EvidenceSha256) > 0 {
		i -= len(m.EvidenceSha256)
		copy(dAtA[i:], m.EvidenceSha256)
		i = encodeVarintVerdict(dAtA, i, uint64(len(m.EvidenceSha256)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Epoch != 0 {
		i = encodeVarintVerdict(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if m.SeatRole != 0 {
		i = encodeVarintVerdict(dAtA, i, uint64(m.SeatRole))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerdict(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerdict(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Verdict) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SeatRole != 0 {
		n += 1 + sovVerdict(uint64(m.SeatRole))
	}
	if m.Epoch != 0 {
		n += 1 + sovVerdict(uint64(m.Epoch))
	}
	l = len(m.EvidenceSha256)
	if l > 0 {
		n += 1 + l + sovVerdict(uint64(l))
	}
	if m.RecordedHeight != 0 {
		n += 1 + sovVerdict(uint64(m.RecordedHeight))
	}
	if m.Punished {
		n += 2
	}
	return n
}

func sovVerdict(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerdict(x uint64) (n int) {
	return sovVerdict(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Verdict) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerdict
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Verdict: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Verdict: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeatRole", wireType)
			}
			m.SeatRole = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeatRole |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerdict
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerdict
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedHeight", wireType)
			}
			m.RecordedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Punished", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Punished = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipVerdict(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerdict
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerdict(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerdict
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerdict
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerdict
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerdict
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerdict
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerdict        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerdict          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerdict = fmt.Errorf("proto: unexpected end of group")
)
